title: Dave Lyon
description: |
  Dave is a freelance software developer focusing on iOS development in Swift and Objective-C.
  
  If you'd like to work with Dave on a contract basis, please reach out to hire@(this domain).

google_analytics: 
show_downloads: false
theme: jekyll-theme-minimal

gems:
  - jekyll-mentions
  - jekyll-sitemap
