title: Dave Lyon - Mobile Software Consultant
description: |
  Dave is a mobile app consultant working with cutting-edge mobile app companies to increase revenue and user-retention.
  
  If you'd like to work with Dave on a contract basis, please reach out to hire@(this domain).

google_analytics: UA-89703059-1
show_downloads: false
theme: jekyll-theme-minimal
permalink: /:categories/:year/:month/:day/:title

gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-seo-tag

twitter:
  username: daveisonthego

author:
  twitter: daveisonthego

