title: Dave Lyon - Freelance iOS Developer
description: |
  Dave is a freelance software developer focusing on iOS development in Swift and Objective-C.
  
  If you'd like to work with Dave on a contract basis, please reach out to hire@(this domain).

google_analytics: UA-89703059-1
show_downloads: false
theme: jekyll-theme-minimal
permalink: /:categories/:year/:month/:day/:title

gems:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-seo-tag

twitter:
  username: daveisonthego

author:
  twitter: daveisonthego

